server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/authdb
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: estaesunallavesecretamuyseguraparajwt1234567890

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
