server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: estaesunallavesecretamuyseguraparajwt1234567890

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
