server:
  port: 8082

spring:
  datasource:
    postgresql
    username: productos_user
    password: productos_pass
    driver-class-name: org.postgresql.Driver
    
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
