spring:
  datasource:
    url: jdbc:postgresql://postgres-usuarios:5432/usuariosdb
    username: usuarios_user
    password: usuarios_pass

jwt:
  secret: "estaesunallavesecretamuyseguraparajwt1234567890"
